In [7]:
from sqlalchemy import create_engine
import pandas as pd

connStr = "mysql+mysqlconnector://root:74090344@localhost:3306/nuclio"
conn = create_engine(connStr).connect()

In [8]:
#Se convierten los archivos de Excel a CSV para facilitar la carga y el manejo de los datos en la bd.


pd.read_excel("ALOJAMIENTO.xlsx").to_csv("ALOJAMIENTO.csv", index=False)
pd.read_excel("UBICACION.xlsx").to_csv("UBICACION.csv", index=False)
pd.read_excel("PRECIO.xlsx").to_csv("PRECIO.csv", index=False)
pd.read_excel("PUNTUACION.xlsx").to_csv("PUNTUACION.csv", index=False)

In [9]:
alojamiento = pd.read_csv("ALOJAMIENTO.csv", sep=',')
ubicacion = pd.read_csv("UBICACION.csv", sep=',')
precio = pd.read_csv("PRECIO.csv", sep=',')
puntuacion = pd.read_csv("PUNTUACION.csv", sep=',')

In [10]:
conn.execute("DROP TABLE IF EXISTS precio")
conn.execute("DROP TABLE IF EXISTS ubicacion")
conn.execute("DROP TABLE IF EXISTS puntuacion")
conn.execute("DROP TABLE IF EXISTS alojamiento")

In [11]:
sSQL_ALOJAMIENTO = """
CREATE TABLE alojamiento (
    codigo_alojamiento VARCHAR(20) NOT NULL,
    nombre VARCHAR(100),
    cant_banyos INT,
    cant_hab INT,
    salon VARCHAR(2),
    terraza VARCHAR(2),
    airec_acond VARCHAR(2),
    piscina VARCHAR(2),
    superficie INT,
    PRIMARY KEY (codigo_alojamiento)
)
"""
conn.execute(sSQL_ALOJAMIENTO)

In [12]:
sSQL_UBICACION = """
CREATE TABLE ubicacion (
    codigo_alojamiento VARCHAR(20) NOT NULL,
    pais VARCHAR(60),
    ciudad VARCHAR(60),
    dist_metro FLOAT,
    dist_centro FLOAT,
    PRIMARY KEY (codigo_alojamiento)
)
"""
conn.execute(sSQL_UBICACION)

In [13]:
# %_RESERVA se implementa como porcentaje_reserva porque el símbolo de porcentaje
# puede generar errores de sintaxis en SQL, y es más claro.

sSQL_PRECIO = """
CREATE TABLE precio (
    codigo_alojamiento VARCHAR(20) NOT NULL,
    precio_alquiler FLOAT,
    reserva VARCHAR(2),
    porcentaje_reserva FLOAT,
    PRIMARY KEY (codigo_alojamiento)
)
"""
conn.execute(sSQL_PRECIO)

In [14]:
sSQL_PUNTUACION = """
CREATE TABLE puntuacion (
    codigo_alojamiento VARCHAR(20) NOT NULL,
    puntos FLOAT,
    agencia VARCHAR(100),
    puntos_agencia FLOAT,
    PRIMARY KEY (codigo_alojamiento)
)
"""
conn.execute(sSQL_PUNTUACION)

In [15]:
conn.execute(("SHOW TABLES")).fetchall()

[('alojamiento',), ('precio',), ('puntuacion',), ('ubicacion',)]

In [16]:
alojamiento.to_sql("alojamiento", conn, index=False, if_exists="append")
ubicacion.to_sql("ubicacion", conn, index=False, if_exists="append")
precio.to_sql("precio", conn, index=False, if_exists="append")
puntuacion.to_sql("puntuacion", conn, index=False, if_exists="append")

20

PRIMERA PARTE

Primer paso: crear la query de cada una de las exigencias del cliente.

In [17]:
# El cliente exige terraza y aire acondicionado, pero no quiere piscina

sSQL = """
SELECT *
FROM alojamiento
WHERE terraza = 'SI'
AND airec_acond = 'SI'
AND piscina = 'NO';
"""
pd.read_sql(sSQL, conn)

,codigo_alojamiento,nombre,cant_banyos,cant_hab,salon,terraza,airec_acond,piscina,superficie
0,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
1,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
2,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
3,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100

In [18]:
# No se alojará en estudios que no tengan salón ni en propiedades con solo un baño

sSQL = """
SELECT *
FROM alojamiento
WHERE NOT (NOMBRE LIKE '%Estudio%' AND SALON = 'NO')
AND CANT_BANYOS > 1;
"""

pd.read_sql(sSQL, conn)

,codigo_alojamiento,nombre,cant_banyos,cant_hab,salon,terraza,airec_acond,piscina,superficie
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
2,ALOJ006,Chalet Vista al Lago,3,4,SI,SI,SI,SI,150
3,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130
4,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85
5,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
6,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110
7,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160
8,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
9,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180
10,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100
11,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95

In [19]:
# La propiedad debe tener como mínimo 80m2

sSQL = """
SELECT *
FROM alojamiento
WHERE superficie >= 80;
"""
pd.read_sql(sSQL, conn)

,codigo_alojamiento,nombre,cant_banyos,cant_hab,salon,terraza,airec_acond,piscina,superficie
0,ALOJ001,Villa Sol del Mar,2,3,SI,SI,SI,SI,120
1,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90
2,ALOJ006,Chalet Vista al Lago,3,4,SI,SI,SI,SI,150
3,ALOJ007,Dúplex Jardines del Sur,2,3,SI,SI,SI,SI,130
4,ALOJ009,Casa Rústica Montaña,2,2,SI,SI,NO,NO,85
5,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88
6,ALOJ012,Villa Palmeras,2,3,SI,SI,SI,SI,110
7,ALOJ013,Apartamento Moderno,1,2,SI,NO,SI,NO,80
8,ALOJ014,Casa del Mar,3,4,SI,SI,SI,SI,160
9,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120
10,ALOJ017,Chalet Jardín Secreto,3,5,SI,SI,SI,SI,180
11,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100
12,ALOJ019,Casa Río Claro,2,2,SI,SI,NO,NO,95

In [20]:
# Como el cliente odia el ruido, no quiere alojarse en propiedades a menos de 1 km
# de una estación de metro ni a menos de 2 km del centro

sSQL = """
SELECT *
FROM ubicacion
WHERE dist_metro >= 1
AND dist_centro >= 2;
"""
pd.read_sql(sSQL, conn)

   codigo_alojamiento      pais     ciudad  dist_metro  dist_centro
0             ALOJ001  Portugal      Liboa         1.0          2.0
1             ALOJ004   Francia   Marsella         3.0          4.0
2             ALOJ005  Portugal     Oporto         4.0          3.0
3             ALOJ006   Francia      Paris         2.0          2.0
4             ALOJ007   Francia   Toulouse         1.0          3.0
5             ALOJ008    España  Barcelona         2.0          3.0
6             ALOJ009    España     Madrid         2.0          4.0
7             ALOJ010    España     Bilbao         2.0          5.0
8             ALOJ015    España     Málaga         2.0          4.0
9             ALOJ016    Italia       Roma         2.0          2.0
10            ALOJ017   Francia      Paris         1.0          2.0
11            ALOJ018    España      Ibiza         2.0          4.0
12            ALOJ019  Portugal      Lagos         2.0          2.0
13            ALOJ020  Portugal    Madeira         3.0          2.0

In [21]:
# El rango permitido por el cliente para pagar es entre 1.500€ y 2.000€ la noche

sSQL = """
SELECT *
FROM precio
WHERE precio_alquiler BETWEEN 1500 AND 2000;
"""
pd.read_sql(sSQL, conn)

   codigo_alojamiento  precio_alquiler reserva  porcentaje_reserva
0             ALOJ001           1800.0      SI               100.0
1             ALOJ004           1600.0      SI                25.0
2             ALOJ008           1500.0      SI                25.0
3             ALOJ009           1600.0      SI               100.0
4             ALOJ010           1750.0      SI                25.0
5             ALOJ011           1825.0      NO                 0.0
6             ALOJ012           1750.0      NO                 0.0
7             ALOJ013           1652.0      NO                 0.0
8             ALOJ014           1941.0      NO                 0.0
9             ALOJ015           1800.0      SI                25.0
10            ALOJ016           2000.0      SI                30.0
11            ALOJ018           1900.0      SI                25.0
12            ALOJ019           1570.0      NO                 0.0
13            ALOJ020           1580.0      NO                 0.0

In [22]:
# Como en anteriores ocasiones ha tenido problemas de intentos de estafas con
# otras agencias, el cliente pide que el % de reserva no sea muy alto, pero
# tampoco tan bajo (porque le genera inseguridad) por lo que propone un 25%

sSQL = """
SELECT *
FROM precio
WHERE porcentaje_reserva = 25;
"""
pd.read_sql(sSQL, conn)

  codigo_alojamiento  precio_alquiler reserva  porcentaje_reserva
0            ALOJ002            780.0      SI                25.0
1            ALOJ004           1600.0      SI                25.0
2            ALOJ008           1500.0      SI                25.0
3            ALOJ010           1750.0      SI                25.0
4            ALOJ015           1800.0      SI                25.0
5            ALOJ018           1900.0      SI                25.0

In [23]:
# Quiere que el alojamiento tenga más de 4,5 puntos de confianza y que la
# agencia que lo lleva tenga más de 4 puntos

sSQL = """
SELECT *
FROM puntuacion
WHERE puntos > 4.5
AND puntos_agencia > 4;
"""
pd.read_sql(sSQL, conn)

   codigo_alojamiento  puntos            agencia  puntos_agencia
0             ALOJ001     5.0         GlobalHome             4.4
1             ALOJ004     4.6         CaribeRent             4.6
2             ALOJ007     4.9       SevillaRooms             4.5
3             ALOJ008     4.8          ChileVive             4.3
4             ALOJ009     4.7         MexicoRent             4.8
5             ALOJ010     4.8          UYAlquila             4.9
6             ALOJ014     4.7        BogotaLodge             4.5
7             ALOJ015     4.9  EasyStay Valencia             4.7
8             ALOJ017     4.9         CuscoRenta             4.4
9             ALOJ018     4.7       MendozaRooms             4.7
10            ALOJ019     4.9            GDLRent             4.2
11            ALOJ020     4.9           VivaStay             4.9

Segundo paso: crear en una única query la combinación de los filtros anteriores para
hallar las propiedades que finalmente cumplen con todas las exigencias del cliente.

In [24]:
sSQL = """

SELECT
    a.codigo_alojamiento,
    a.nombre,
    a.cant_banyos,
    a.cant_hab,
    a.salon,
    a.terraza,
    a.airec_acond,
    a.piscina,
    a.superficie,
    u.pais,
    u.ciudad,
    u.dist_metro,
    u.dist_centro,
    p.precio_alquiler,
    p.reserva,
    p.porcentaje_reserva,
    pu.puntos,
    pu.agencia,
    pu.puntos_agencia
FROM alojamiento a
INNER JOIN ubicacion u
    ON a.codigo_alojamiento = u.codigo_alojamiento
INNER JOIN precio p
    ON a.codigo_alojamiento = p.codigo_alojamiento
INNER JOIN puntuacion pu
    ON a.codigo_alojamiento = pu.codigo_alojamiento
WHERE a.terraza = 'SI'
    AND a.airec_acond = 'SI'
    AND a.piscina = 'NO'
    AND a.CANT_BANYOS > 1 -- Más de un baño
    AND NOT (a.NOMBRE LIKE '%Estudio%' AND a.SALON = 'NO')
    AND a.superficie >= 80
    AND u.dist_metro >= 1
    AND u.dist_centro >= 2
    AND p.precio_alquiler BETWEEN 1500 AND 2000
    AND p.porcentaje_reserva = 25
    AND pu.puntos > 4.5
    AND pu.puntos_agencia > 4
"""

pd.read_sql(sSQL, conn)

,codigo_alojamiento,nombre,cant_banyos,cant_hab,salon,terraza,airec_acond,piscina,superficie,pais,ciudad,dist_metro,dist_centro,precio_alquiler,reserva,porcentaje_reserva,puntos,agencia,puntos_agencia
0,ALOJ004,Piso Centro Histórico,2,3,SI,SI,SI,NO,90,Francia,Marsella,3.0,4.0,1600.0,SI,25.0,4.6,CaribeRent,4.6
1,ALOJ010,Ático del Sol,3,3,SI,SI,SI,NO,88,España,Bilbao,2.0,5.0,1750.0,SI,25.0,4.8,UYAlquila,4.9
2,ALOJ015,Dúplex Las Rocas,3,4,SI,SI,SI,NO,120,España,Málaga,2.0,4.0,1800.0,SI,25.0,4.9,EasyStay Valencia,4.7
3,ALOJ018,Piso Parque Central,2,4,SI,SI,SI,NO,100,España,Ibiza,2.0,4.0,1900.0,SI,25.0,4.7,MendozaRooms,4.7

Tercer paso: Como habéis visto, tenemos 4 propiedades que cumplen con todas las
exigencias de nuestro cliente, ahora bien, desde tu punto de vista, haciendo un análisis de
los datos del cliente y de todas sus exigencias ¿Cuál de estos 4 alojamientos le
recomendarías y por qué?

- Le recomendaría al cliente el Dúplex Las Rocas (Málaga), ya que es la alternativa que mejor se ajusta a sus criterios. Su localización en la Costa del Sol cumple con el requisito principal de disfrutar el sol en una buena playa. Asimismo, al viajar con un grupo familiar de ocho personas, las cuatro habitaciones y tres baños son fundamentales para garantizar la comodidad de todos, siendo además la propiedad de mayor tamaño entre las cuatro opciones analizadas. Aunque el Piso Parque Central también dispone de cuatro habitaciones, el entorno de Ibiza en plena temporada alta supondría una exposición mediática constante; por el contrario, Málaga permite un descanso real, lejos de los focos y la prensa, cumpliendo con el objetivo de descansar y pasar desapercibido antes de su gira de septiembre. Además, el Dúplex Las Rocas tiene la puntuación más alta entre las opciones analizadas (4,9), lo que asegura una experiencia de calidad y reduce el riesgo de sufrir fraude o estafa durante su estancia.

SEGUNDA PARTE

In [25]:
# ¿Cuál es la suma total de metros cuadrados de los alojamientos que tienen piscina?

sSQL = """
SELECT SUM(superficie) AS total_metros_cuadrados
FROM alojamiento
WHERE piscina = 'SI';
"""

pd.read_sql(sSQL, conn)

   total_metros_cuadrados
0                   850.0

In [26]:
# ¿Cuál es el alojamiento con mayor superficie?

sSQL = """
SELECT codigo_alojamiento, nombre, superficie
FROM alojamiento
WHERE superficie = (SELECT MAX(superficie) FROM alojamiento);
"""

pd.read_sql(sSQL, conn)

  codigo_alojamiento                 nombre  superficie
0            ALOJ017  Chalet Jardín Secreto         180

In [27]:
#¿Cuál es el alojamiento con menor superficie?

sSQL = """
SELECT codigo_alojamiento, nombre, superficie
FROM alojamiento
WHERE superficie = (SELECT MIN(superficie) FROM alojamiento);
"""

pd.read_sql(sSQL, conn)

  codigo_alojamiento          nombre  superficie
0            ALOJ016  Estudio Urbano          35

In [28]:
# ¿Cuántos alojamientos tienen salón?

sSQL = """
SELECT COUNT(*) AS alojamientos_con_salon
FROM alojamiento
WHERE salon = 'SI';
"""

pd.read_sql(sSQL, conn)

   alojamientos_con_salon
0                      16

In [29]:
# - ¿Cuántos alojamientos tienen terraza?

sSQL = """
SELECT COUNT(*) AS total_con_terraza
FROM alojamiento
WHERE terraza = 'SI';
"""

pd.read_sql(sSQL, conn)

   total_con_terraza
0                 14

In [30]:
# ¿Cuántos alojamientos hay por cada país según nuestra tabla de UBICACIÓN?

sSQL = """
SELECT pais, COUNT(*) AS alojamientos_por_pais
FROM ubicacion
GROUP BY pais;
"""

pd.read_sql(sSQL, conn)

       pais  alojamientos_por_pais
0  Portugal                      4
1    España                      8
2   Francia                      4
3    Italia                      4

In [31]:
# ¿Cuál es el promedio de precios de alquiler de todos los alojamientos según la tabla precio?

sSQL = """
SELECT (AVG(precio_alquiler)) AS precio_promedio
FROM precio;
"""

pd.read_sql(sSQL, conn)

   precio_promedio
0           1568.4

In [32]:
# ¿Cuáles son las 3 agencias que tienen la mayor puntuación de agencia (campo a
# usar: PUNTOS_AGENCIA) según la tabla PUNTUACION?

sSQL = """
SELECT agencia, puntos_agencia,
    ranking
FROM (
    SELECT agencia, puntos_agencia,
        RANK() OVER (ORDER BY puntos_agencia DESC) AS ranking
    FROM puntuacion) AS tabla_ranking
WHERE ranking <= 3;
"""

pd.read_sql(sSQL, conn)

         agencia  puntos_agencia  ranking
0     TerraHouse             4.9        1
1      UYAlquila             4.9        1
2  MalagaTurismo             4.9        1
3       VivaStay             4.9        1

Dado que hay un empate en la puntuación más alta (4.9), he utilizado la función RANK() según el campo PUNTOS_AGENCIA. En este caso, son 4 las agencias que tienen la mayor puntuación.

In [34]:
# Muestra los alojamientos (código y nombre) que: Contengan la palabra ‘Piso’ en su
# nombre o que tengan piscina y aire acondicionado, pero no pasen los 150 metros
# de superficie o que tengan más de un baño

sSQL = """
SELECT codigo_alojamiento, nombre
FROM alojamiento
WHERE nombre LIKE '%Piso%'
    OR (piscina = 'SI' AND airec_acond = 'SI' AND superficie <= 150)
    OR cant_banyos > 1;
"""

pd.read_sql(sSQL, conn)

   codigo_alojamiento                   nombre
0             ALOJ001        Villa Sol del Mar
1             ALOJ004    Piso Centro Histórico
2             ALOJ006     Chalet Vista al Lago
3             ALOJ007  Dúplex Jardines del Sur
4             ALOJ009     Casa Rústica Montaña
5             ALOJ010            Ático del Sol
6             ALOJ012           Villa Palmeras
7             ALOJ014             Casa del Mar
8             ALOJ015         Dúplex Las Rocas
9             ALOJ017    Chalet Jardín Secreto
10            ALOJ018      Piso Parque Central
11            ALOJ019           Casa Río Claro

In [35]:
# Muestra una consulta que muestre el código de alojamiento, el nombre, el precio y
# una columna donde veamos el precio del alquiler con el símbolo del euro al final de
# cada importe, esta nueva columna se debe llama PRECIO_MODIF

sSQL = """
SELECT
    a.codigo_alojamiento,
    a.nombre,
    p.precio_alquiler,
    CONCAT(p.precio_alquiler, ' €') AS PRECIO_MODIF
FROM alojamiento a
INNER JOIN precio p
    ON a.codigo_alojamiento = p.codigo_alojamiento;
"""

pd.read_sql(sSQL, conn)

   codigo_alojamiento                    nombre  precio_alquiler PRECIO_MODIF
0             ALOJ001         Villa Sol del Mar           1800.0       1800 €
1             ALOJ002  Apartamento Las Palmeras            780.0        780 €
2             ALOJ003         Cabaña El Refugio            800.0        800 €
3             ALOJ004     Piso Centro Histórico           1600.0       1600 €
4             ALOJ005      Estudio Playa Blanca            900.0        900 €
5             ALOJ006      Chalet Vista al Lago           1200.0       1200 €
6             ALOJ007   Dúplex Jardines del Sur           1300.0       1300 €
7             ALOJ008               Loft Urbano           1500.0       1500 €
8             ALOJ009      Casa Rústica Montaña           1600.0       1600 €
9             ALOJ010             Ático del Sol           1750.0       1750 €
10            ALOJ011   Cabaña Bosque Encantado           1825.0       1825 €
11            ALOJ012            Villa Palmeras           1750.0       1750 €
12            ALOJ013       Apartamento Moderno           1652.0       1652 €
13            ALOJ014              Casa del Mar           1941.0       1941 €
14            ALOJ015          Dúplex Las Rocas           1800.0       1800 €
15            ALOJ016            Estudio Urbano           2000.0       2000 €
16            ALOJ017     Chalet Jardín Secreto           2120.0       2120 €
17            ALOJ018       Piso Parque Central           1900.0       1900 €
18            ALOJ019            Casa Río Claro           1570.0       1570 €
19            ALOJ020       Loft Estación Norte           1580.0       1580 €

In [36]:
# Muestra una columna sobre la tabla PRECIO que se llame CATEGORIA_PRECIO y
# que indique la palabra ‘Bajo’ si el precio está entre 780 y 1000, ‘Medio’ si el precio
# está entre 1000 y 1700 y ‘Alto’ si es mayor a 1700

sSQL = """
SELECT
    codigo_alojamiento,
    precio_alquiler,
    CASE
        WHEN precio_alquiler BETWEEN 780 AND 1000 THEN 'Bajo'
        WHEN precio_alquiler <= 1700 THEN 'Medio'
        ELSE 'Alto'
    END AS CATEGORIA_PRECIO
FROM precio;
"""

pd.read_sql(sSQL, conn)

   codigo_alojamiento  precio_alquiler CATEGORIA_PRECIO
0             ALOJ001           1800.0             Alto
1             ALOJ002            780.0             Bajo
2             ALOJ003            800.0             Bajo
3             ALOJ004           1600.0            Medio
4             ALOJ005            900.0             Bajo
5             ALOJ006           1200.0            Medio
6             ALOJ007           1300.0            Medio
7             ALOJ008           1500.0            Medio
8             ALOJ009           1600.0            Medio
9             ALOJ010           1750.0             Alto
10            ALOJ011           1825.0             Alto
11            ALOJ012           1750.0             Alto
12            ALOJ013           1652.0            Medio
13            ALOJ014           1941.0             Alto
14            ALOJ015           1800.0             Alto
15            ALOJ016           2000.0             Alto
16            ALOJ017           2120.0             Alto
17            ALOJ018           1900.0             Alto
18            ALOJ019           1570.0            Medio
19            ALOJ020           1580.0            Medio

In [37]:
conn.close()